"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.genNonce = exports.genStarkKey = exports.simplifyOnboarding = exports.basicOnboarding = exports.solidityKeccak256 = void 0;
var cal_1 = require("./cal");
Object.defineProperty(exports, "solidityKeccak256", { enumerable: true, get: function () { return cal_1.solidityKeccak256; } });
var starkKey_1 = require("./starkKey");
Object.defineProperty(exports, "basicOnboarding", { enumerable: true, get: function () { return starkKey_1.basicOnboarding; } });
Object.defineProperty(exports, "simplifyOnboarding", { enumerable: true, get: function () { return starkKey_1.simplifyOnboarding; } });
Object.defineProperty(exports, "genStarkKey", { enumerable: true, get: function () { return starkKey_1.genStarkKey; } });
Object.defineProperty(exports, "genNonce", { enumerable: true, get: function () { return starkKey_1.genNonce; } });
